TestTask.UI/Controllers/AuthorController.cs
using AutoMapper;
using System.Web.Mvc;
using TestTask.BLL.Services.AuthorService;
using TestTask.UI.Models;

namespace TestTask.UI.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorService _authorService;
        private readonly IMapper _mapper;

        public AuthorController(IAuthorService authorService,
                                IMapper mapper)
        {
            _authorService = authorService;
            _mapper = mapper;
        }

        public ActionResult Index(int? itemsCount, int? page)
        {
            var authorsWithPageDto = _authorService.GetAuthorsWithPageDto(page, itemsCount);
            var authorsWithPageViewModel = _mapper.Map<AuthorsWithPageViewModel>(authorsWithPageDto);
            
            return View(authorsWithPageViewModel);
        }
    }
}

TestTask.UI/Controllers/BookController.cs
using AutoMapper;
using System.Web.Mvc;
using TestTask.BLL.Services.BookService;
using TestTask.BLL.Services.BookService.Dtos;
using TestTask.UI.Models;

namespace TestTask.UI.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IMapper _mapper;

        public BookController(IBookService bookService,
                              IMapper mapper)
        {
            _bookService = bookService;
            _mapper = mapper;
        }

        [HttpGet]
        public ActionResult Index(int? page, int? itemsCount)
        {
            var booksWithPageDto = _bookService.GetBooksWithPageDto(page, itemsCount);
            var booksWithPageViewModel = _mapper.Map<BooksWithPageViewModel>(booksWithPageDto);

            return View(booksWithPageViewModel);
        }

        [HttpPost]
        public ActionResult Index(int? page, int? itemsCount, SearchBookViewModel searchBook)
        {
            var searchBookDto = _mapper.Map<SearchBookDto>(searchBook);
            var booksWithPageDto = _bookService.GetBooksWithPageDto(page, itemsCount, searchBookDto);
            var booksWithPageViewModel = _mapper.Map<BooksWithPageViewModel>(booksWithPageDto);

            return View(booksWithPageViewModel);
        }

        [HttpGet]
        public ActionResult AddBook()
        {
            var bookDto = new BookDto();
            var bookViewModel = _mapper.Map<BookViewModel>(bookDto);

            return View(bookViewModel);
        }

        [HttpPost]
        public ActionResult AddBook(BookViewModel book)
        {
            var bookDto = _mapper.Map<BookDto>(book);

            if (!ModelState.IsValid)
            {
                return View(book);
            }

            _bookService.CreateBook(bookDto);

            return RedirectToAction(nameof(Index));
        }

        public ActionResult BookDetails(int id)
        {
            var bookDto = _bookService.GetBook(id);
            var bookViewModel = _mapper.Map<BookViewModel>(bookDto);

            return PartialView($"_{nameof(BookDetails)}", bookViewModel);
        }

        public ActionResult EditBook(int id)
        {
            var bookDto = _bookService.GetBook(id);
            var bookViewModel = _mapper.Map<BookViewModel>(bookDto);

            return View(bookViewModel);
        }

        [HttpPost]
        public ActionResult EditBook(BookViewModel book)
        {
            var bookDto = _mapper.Map<BookDto>(book);

            if (!ModelState.IsValid)
            {
                var bookView = _mapper.Map<BookViewModel>(bookDto);

                return View(bookView);
            }

            _bookService.UpdateBook(bookDto);

            return RedirectToAction(nameof(Index));
        }
    }
}

TestTask.UI/Controllers/GenreController.cs
using AutoMapper;
using System.Web.Mvc;
using TestTask.BLL.Services.GenreService;
using TestTask.UI.Models;

namespace TestTask.UI.Controllers
{
    public class GenreController : Controller
    {
        private readonly IGenreService _genreService;
        private readonly IMapper _mapper;

        public GenreController(IGenreService genreService,
                               IMapper mapper)
        {
            _genreService = genreService;
            _mapper = mapper;
        }

        public ActionResult Index(int? page, int? itemsCount)
        {
            var genresWithPageDto = _genreService.GetGenresWithPageDto(page, itemsCount);
            var genresWithPageViewModel = _mapper.Map<GenresWithPageViewModel>(genresWithPageDto);

            return View(genresWithPageViewModel);
        }
    }
}

TestTask.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Библиотека &#34;Алые паруса&#34; - @ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/select2.min.css")" rel="stylesheet" type="text/css" />
    @Scripts.Render("~/Scripts/jquery-3.4.1.min.js")
    @Scripts.Render("~/Scripts/select2.min.js")
    @Scripts.Render("~/Scripts/select.authors.min.js")
    @Scripts.Render("~/Scripts/select.genres.min.js")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
</head>

<body>
    <div class="menu">
        <ul>
            <li>@Html.ActionLink("Главная", "Index", "Home")</li>
            <li>@Html.ActionLink("Книги", "Index", "Book")</li>
            <li>@Html.ActionLink("Авторы", "Index", "Author")</li>
            <li>@Html.ActionLink("Жанры", "Index", "Genre")</li>
        </ul>
    </div>
    @RenderBody()
</body>
</html>

TestTask.UI/Views/Shared/_paging.cshtml
<div>
    @{
        var leftLeft = Model.PageInfo.PageNumber - 2;
        var left = Model.PageInfo.PageNumber - 1;
        var right = Model.PageInfo.PageNumber + 1;
        var rightRight = Model.PageInfo.PageNumber + 2;
        var itemsCountPerPage = Model.PageInfo.ItemsCountPerPage;
        var pageNumber = Model.PageInfo.PageNumber;
        var pagesCount = Model.PageInfo.PagesCount;
    }

    @if (pageNumber > 1)
    {
        @Html.RouteLink("<<", new { page = 1, itemsCount = itemsCountPerPage })
        @Html.RouteLink("<", new { page = left, itemsCount = itemsCountPerPage })
    }

    @if (pageNumber > 2)
    {
        @Html.RouteLink($"{leftLeft}", new { page = leftLeft, itemsCount = itemsCountPerPage })
    }

    @if (pageNumber > 1)
    {
        @Html.RouteLink($"{left}", new { page = left, itemsCount = itemsCountPerPage })
    }

    @Html.RouteLink($"{pageNumber}", new { page = pageNumber, itemsCount = itemsCountPerPage })

    @if (pageNumber <= pagesCount - 1)
    {
        @Html.RouteLink($"{right}", new { page = right, itemsCount = itemsCountPerPage })
    }

    @if (pageNumber <= pagesCount - 2)
    {
        @Html.RouteLink($"{rightRight}", new { page = rightRight, itemsCount = itemsCountPerPage })
    }

    @if (pageNumber < pagesCount)
    {
        @Html.RouteLink(">", new { page = right, itemsCount = itemsCountPerPage })
        @Html.RouteLink(">>", new { page = pagesCount, itemsCount = itemsCountPerPage })
    }
</div>